"""empty message

Revision ID: 664f3f6d4868
Revises: a5cffa318ac2
Create Date: 2023-12-27 19:23:12.664922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664f3f6d4868'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('favorite_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movies_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'movies_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
